# Generated by Django 3.1.1 on 2020-09-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obituary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('system', models.CharField(default='D&D 5e', max_length=50)),
                ('level', models.IntegerField()),
                ('story', models.CharField(max_length=280)),
            ],
        ),
    ]
